In [1]:
%load_ext autoreload
%autoreload 2

In [21]:
import numpy as np
import pandas as pd
import plotly.express as px
from pathlib import Path

In [ ]:
weather_dirpath = Path('../../data/raw/weather_owm')
coords = []
for filepath in weather_dirpath.glob('*.json'):
    parts = filepath.stem.split('_')
    lat = float('.'.join(parts[1:3]))
    lon = float('.'.join(parts[3:5]))
    coords.append((lat, lon))
coords

[(51.6956, 75.3297),
 (47.247706, 52.465977),
 (46.862232, 73.500071),
 (47.885021, 68.555921),
 (50.333435, 57.162802),
 (53.257756, 63.701736),
 (53.221389, 64.580278),
 (50.397318, 81.069005),
 (51.234698, 51.405632),
 (49.980758, 82.615375),
 (42.845057, 71.480839),
 (52.406688, 64.082731),
 (42.161097, 69.761446),
 (51.0271, 71.4607),
 (51.2033, 61.4431),
 (45.495101, 64.114344),
 (42.859331, 73.211756),
 (44.18764, 66.719456),
 (43.476747, 73.647966),
 (48.608459, 57.109526),
 (43.033564, 78.83436),
 (49.921055, 83.085657),
 (50.271911, 127.49593),
 (43.622656, 78.596191),
 (41.25273, 67.967631),
 (52.211445, 76.911346),
 (51.627527, 69.836461),
 (46.776875, 54.532018),
 (43.610907, 76.962575),
 (51.267981, 51.096781),
 (45.086392, 51.387305),
 (43.082778, 76.976111),
 (46.732508, 49.735043),
 (50.063887, 72.986541),
 (50.188422, 51.165903),
 (49.802287, 72.864697),
 (52.164818, 61.269958),
 (42.432744, 68.813798),
 (48.548004, 57.564817),
 (50.513153, 58.261809),
 (47.675556, 51.578333),
 (43.215665, 76.312408),
 (43.249595, 76.916108),
 (51.8725, 67.824722),
 (50.270581, 66.950169),
 (44.878225, 78.713781),
 (49.349898, 57.233362),
 (42.716473, 70.814864),
 (50.025821, 82.782778),
 (44.855262, 65.508289),
 (49.705319, 72.552306),
 (50.907352, 72.048327),
 (51.796567, 68.306165),
 (41.089267, 68.690142),
 (45.207229, 73.965991),
 (52.65133, 66.586842),
 (52.541516, 63.200954),
 (43.596578, 78.255734),
 (49.511667, 72.796389),
 (52.278655, 77.039973),
 (43.904139, 67.253822),
 (43.599252, 51.292859),
 (50.254504, 82.273479),
 (49.818549, 72.653944),
 (48.846667, 72.826389),
 (43.529332, 69.68728),
 (41.718253, 69.013),
 (44.328611, 53.54),
 (50.161202, 73.168387),
 (45.102402, 73.970046),
 (43.161389, 70.465),
 (46.427304, 65.702311),
 (50.24969, 73.039297),
 (53.311314, 68.054702),
 (43.424556, 77.017989),
 (43.892884, 77.077604),
 (42.548777, 70.001677),
 (52.034982, 75.462293),
 (51.626111, 73.743056),
 (53.318018, 68.917365),
 (48.676578, 71.611006),
 (47.230556, 73.351667),
 (51.631338, 73.176971),
 (42.256289, 70.099979),
 (49.80776, 73.088504),
 (53.757164, 62.048006),
 (47.97432, 74.034435),
 (47.311188, 52.297297),
 (51.003841, 68.163981),
 (51.450781, 53.389608),
 (44.354167, 77.951111),
 (46.844352, 74.947067),
 (50.270375, 57.54173),
 (47.096851, 51.933558),
 (51.067752, 79.408855),
 (54.498458, 69.442657),
 (50.560583, 72.548935),
 (53.355541, 68.577863),
 (53.316922, 69.416996),
 (51.642273, 75.464475),
 (46.119722, 73.603333),
 (51.912093, 67.322534),
 (43.797609, 74.376869),
 (42.306153, 69.634161),
 (43.753086, 69.195345),
 (41.346802, 68.950432),
 (49.218445, 81.206114),
 (45.430544, 74.320759),
 (51.260137, 71.861319),
 (47.508621, 72.906142),
 (43.534722, 75.340833),
 (48.755253, 82.381214),
 (42.527417, 70.278896),
 (45.349197, 55.164328),
 (51.934357, 66.386948),
 (44.566856, 73.86216),
 (44.308127, 66.96417),
 (48.572937, 51.644368),
 (43.377778, 73.611667),
 (54.9125, 69.16529),
 (47.785163, 67.744403),
 (54.198579, 69.651381),
 (48.286114, 72.892382),
 (42.774807, 68.371585),
 (47.890453, 67.528974),
 (46.9772, 74.986432),
 (43.498287, 68.49813),
 (53.077297, 70.309969),
 (50.114219, 82.947029),
 (48.032297, 70.798323),
 (42.852279, 71.090004),
 (43.539684, 75.214666),
 (45.949915, 65.693581),
 (50.873127, 51.131609),
 (49.460278, 57.417778),
 (51.18343, 73.868201),
 (42.260116, 69.353368),
 (51.843575, 74.267855),
 (46.950738, 53.925619),
 (45.413718, 79.917122),
 (50.353789, 83.484177),
 (46.942409, 79.655673),
 (46.186322, 53.398155),
 (49.915568, 73.23708),
 (52.545399, 62.074871),
 (51.17521, 71.498711),
 (47.877892, 72.957313),
 (45.002384, 78.38327),
 (48.316087, 74.981362),
 (43.265192, 68.483348),
 (53.380257, 62.851517),
 (51.818769, 75.336415),
 (43.619736, 76.315155),
 (49.89903, 82.714195),
 (52.483558, 72.034092),
 (49.658517, 83.347435),
 (45.095376, 64.688007),
 (43.515904, 52.115907),
 (43.589048, 73.742836),
 (43.354708, 52.791216),
 (52.996282, 63.068354),
 (52.556173, 62.527624),
 (50.935224, 81.375542),
 (48.363202, 57.429878),
 (43.873306, 74.141665),
 (53.07727, 63.345494),
 (53.21107, 66.72379),
 (44.72218, 65.893614),
 (52.639607, 70.452747),
 (43.377531, 76.730231),
 (48.257747, 70.21146),
 (42.089534, 68.976609)]

In [35]:
# Sample data with latitude and longitude
df = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])
df['type'] = 'weather_station'

# Create a geographical scatter plot
fig = px.scatter_geo(df, 
                        lat='Latitude',
                        lon='Longitude',
                     title='Weather Station Coordinates',)
fig.update_geos(
    showcountries=True, countrycolor="Black",
    showsubunits=True, subunitcolor="Brown",
    showland=True, landcolor="LightGreen",
    showocean=True, oceancolor="LightBlue",
    showframe=True, framecolor="DarkGrey",
    resolution=50 # or 110
)
fig.show()

In [36]:
DEFAULT_LAT = 43.256700
DEFAULT_LON = 76.928600

dfs = []
for filepath in Path('../../data/raw/ss_coords').glob('*.xlsx'):
    mes_name = filepath.stem
    df_ss = pd.read_excel(filepath)
    mask = \
        (df_ss['lat'] != ':atom:null') & \
        (df_ss['lon'] != ':atom:null') 
    df_ss = df_ss[mask]
    df_ss['lat'] = df_ss['lat'].astype(float)
    df_ss['lon'] = df_ss['lon'].astype(float)
    mask = ~((np.isclose(df_ss['lat'], DEFAULT_LAT, atol=1e-2)) & (np.isclose(df_ss['lon'], DEFAULT_LON, atol=1e-2))) & \
        (df_ss['lat'] >= 40.66667) & (df_ss['lat'] <= 54.90521) & \
        (df_ss['lon'] >= 46.84705) & (df_ss['lon'] <= 84.87144) & \
        (df_ss['lat'].notna()) & (df_ss['lon'].notna())
    df_ss = df_ss[mask]
    df_ss = df_ss[['prototype@weather', 'lat', 'lon']]
    df_ss['prototype@weather'] = '/' + df_ss['prototype@weather'].str.split('/').str[2:-1].str.join('/')

    # Add "/{mes_name}" row with default coordinates
    # calculate them as mean cooridnates of \
    # all other stations except ones that has "@regions" in their names
    non_region_mask = ~df_ss['prototype@weather'].str.contains('@regions')
    df_ss = pd.concat([
        df_ss,
        pd.DataFrame([{
            'prototype@weather': f'/{mes_name}',
            'lat': df_ss.loc[non_region_mask, 'lat'].mean(),
            'lon': df_ss.loc[non_region_mask, 'lon'].mean(),
        }])
    ], ignore_index=True)

    dfs.append(df_ss)
df_all_ss = pd.concat(dfs, ignore_index=True)
display(df_all_ss[df_all_ss.duplicated(subset=['prototype@weather'], keep=False)].sort_values(by='prototype@weather'))
# Manually set 
# /SEVER
# /ALMATY
# /VOSTOK
# /CENTER
# /KOSTANAY
df_all_ss['type'] = 'substation'
df_all_ss

Empty DataFrame
Columns: [prototype@weather, lat, lon]
Index: []

                    prototype@weather        lat        lon        type
0                      /AKTOBE/Zhazyk  51.303995  51.209345  substation
1                    /AKTOBE/Uzlovaya  51.446499  51.265491  substation
2                   /AKTOBE/Ural_GTES  51.483871  51.272455  substation
3                       /AKTOBE/U_TEC  51.423282  51.222241  substation
4                /AKTOBE/Karachaganak  53.389608  51.450781  substation
5                    /AKTOBE/GTES-200  51.099005  51.266977  substation
6                    /AKTOBE/Chapaevo  51.131609  50.873127  substation
7             /AKTOBE/@regions/Aktobe  50.283900  57.167000  substation
8                             /AKTOBE  51.611124  51.222917  substation
9                              /SEVER        NaN        NaN  substation
10                   /AKMOLA/Stepnaya  51.094558  51.268984  substation
11        /AKMOLA/@regions/SevKaz_obl  54.873200  69.150500  substation
12  /AKMOLA/@regions/North Kazakhstan  54.873200  69.150500  substation
13         /AKMOLA/@regions/Kokshetau  53.287100  69.404400  substation
14            /AKMOLA/@regions/Akmola  51.165500  71.427200  substation
15                            /AKMOLA  51.094558  51.268984  substation
16            /ALMATY/@regions/Almaty  43.238000  76.882900  substation
17                            /ALMATY        NaN        NaN  substation
18   /VOSTOK/@regions/East Kazakhstan  49.950000  82.620000  substation
19                            /VOSTOK        NaN        NaN  substation
20            /CENTER/@regions/Ulytau  47.796400  67.702000  substation
21         /CENTER/@regions/Karaganda  48.768000  73.673700  substation
22                            /CENTER        NaN        NaN  substation
23                   /UZHNIY/Jambyl_T  43.534722  75.340833  substation
24               /UZHNIY/Baikonyr_SES  44.722180  65.893614  substation
25           /UZHNIY/@regions/Zhambyl  43.688200  73.753700  substation
26         /UZHNIY/@regions/Turkestan  42.320500  69.587600  substation
27         /UZHNIY/@regions/KysylOrda  44.848800  65.482300  substation
28                            /UZHNIY  44.128451  70.617223  substation
29        /KOSTANAY/@regions/Kostanay  53.219800  63.635400  substation
30                          /KOSTANAY        NaN        NaN  substation
31                     /ZAPAD/Nursaya  51.877222  47.112222  substation
32                    /ZAPAD/Mahambet  51.578333  47.675556  substation
33                    /ZAPAD/Kashagan  52.465977  47.247706  substation
34                    /ZAPAD/KUS_GTES  52.277412  47.344304  substation
35                    /ZAPAD/Atyr_TEC  51.942147  47.081687  substation
36                   /ZAPAD/ANPZCRP-3  51.921376  47.077180  substation
37          /ZAPAD/@regions/Mangystau  43.658800  51.197500  substation
38             /ZAPAD/@regions/Atyrau  47.094500  51.923800  substation
39                             /ZAPAD  52.010411  47.256442  substation

In [38]:
df_merged = pd.concat(
    [
        df_all_ss[['type', 'lat', 'lon']],
        df[['type', 'Latitude', 'Longitude']].rename(columns={
            'Latitude': 'lat',
            'Longitude': 'lon'
        }),
    ],
    ignore_index=True
)
df_merged

                type        lat        lon
0         substation  51.303995  51.209345
1         substation  51.446499  51.265491
2         substation  51.483871  51.272455
3         substation  51.423282  51.222241
4         substation  53.389608  51.450781
..               ...        ...        ...
207  weather_station  44.722180  65.893614
208  weather_station  52.639607  70.452747
209  weather_station  43.377531  76.730231
210  weather_station  48.257747  70.211460
211  weather_station  42.089534  68.976609

[212 rows x 3 columns]

In [42]:
# Create a geographical scatter plot
fig = px.scatter_geo(df_merged, 
                        lat='lat',
                        lon='lon',
                     title='Coordinates',
                     color='type',
                     symbol='type',
                    
                     )
fig.update_geos(
    showcountries=True, countrycolor="Black",
    showsubunits=True, subunitcolor="Brown",
    showland=True, landcolor="LightGreen",
    showocean=True, oceancolor="LightBlue",
    showframe=True, framecolor="DarkGrey",
    resolution=50 # or 110
)
fig.show()